local:
  persistence: true
admin:
  authType: DeviceFlow
  endpoint: dns:///tryv2.hosted.unionai.cloud
image:
  builder: remote
local:
  persistence: true
task:
  domain: development
  org: tryv2
  project: langfeb
